import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

// ─── Shared helpers ────────────────────────────────────────────────────────────

const BRAND_COLOR  = [30, 100, 220];
const HEADER_GRAY  = [245, 246, 248];
const TEXT_DARK    = [20, 20, 30];
const TEXT_MUTED   = [110, 118, 130];
const BORDER_LIGHT = [220, 224, 230];

function newDoc() {
  return new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
}

// Blue header band. Returns Y after the band.
function drawPageHeader(doc, docType, subTitle = "") {
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(...BRAND_COLOR);
  doc.rect(0, 0, W, 22, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(255, 255, 255);
  doc.text("CARGODESK", 14, 14);

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(docType, W - 14, 9, { align: "right" });
  if (subTitle) {
    doc.setFontSize(7.5);
    doc.text(subTitle, W - 14, 15, { align: "right" });
  }
  return 28;
}

// Two-column label/value meta box with a light background.
// Each row: [leftLabel, leftValue, rightLabel?, rightValue?]
// Right column is skipped entirely when rightLabel and rightValue are both absent/empty.
function drawMetaBox(doc, y, rows) {
  const W      = doc.internal.pageSize.getWidth();
  const margin = 14;
  const boxW   = W - margin * 2;   // 182 mm on A4
  const rowH   = 7;
  const LABEL_W = 36;              // label column width
  const MID     = margin + boxW / 2; // centre of page content

  // Column x-positions
  const LLX = margin;            // left label
  const LVX = margin + LABEL_W;  // left value  (has ~55 mm before centre)
  const RLX = MID;               // right label
  const RVX = MID + LABEL_W;     // right value (has ~55 mm before right margin)

  doc.setFillColor(...HEADER_GRAY);
  doc.roundedRect(margin, y, boxW, rows.length * rowH + 4, 2, 2, "F");

  let cy = y + 6;
  rows.forEach(([ll, lv, rl, rv]) => {
    // Left label
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(...TEXT_MUTED);
    doc.text(String(ll || ""), LLX, cy);

    // Left value
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(...TEXT_DARK);
    doc.text(String(lv || "—"), LVX, cy);

    // Right column — only rendered when at least one of label/value is non-empty
    const hasRight = (rl && rl.trim()) || (rv !== undefined && rv !== null && String(rv).trim() !== "");
    if (hasRight) {
      if (rl) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7);
        doc.setTextColor(...TEXT_MUTED);
        doc.text(String(rl), RLX, cy);
      }
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(...TEXT_DARK);
      doc.text(String(rv !== undefined && rv !== null && rv !== "" ? rv : "—"), RVX, cy);
    }

    cy += rowH;
  });

  return cy + 2;
}

function drawSectionHeading(doc, y, title) {
  const W = doc.internal.pageSize.getWidth();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(...TEXT_MUTED);
  doc.text(title.toUpperCase(), 14, y + 4);
  doc.setDrawColor(...BORDER_LIGHT);
  doc.line(14 + doc.getTextWidth(title.toUpperCase()) + 3, y + 3, W - 14, y + 3);
  return y + 9;
}

function drawDraftWatermark(doc) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  doc.saveGraphicsState();
  doc.setGState(new doc.GState({ opacity: 0.06 }));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(72);
  doc.setTextColor(0, 0, 0);
  doc.text("DRAFT", W / 2, H / 2, { align: "center", angle: 45, baseline: "middle" });
  doc.restoreGraphicsState();
}

function drawFooter(doc, note = "") {
  const W  = doc.internal.pageSize.getWidth();
  const H  = doc.internal.pageSize.getHeight();
  const ts = new Date().toLocaleString("en-GB", { dateStyle: "medium", timeStyle: "short" });
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...TEXT_MUTED);
  doc.text(`Generated by CargoDesk · ${ts}`, 14, H - 7);
  if (note) doc.text(note, W / 2, H - 7, { align: "center" });
  doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber}`, W - 14, H - 7, { align: "right" });
}

// ─── Auto-table shared theme ──────────────────────────────────────────────────

const TABLE_STYLES = {
  theme:      "plain",
  styles:     { fontSize: 8, cellPadding: { top: 3, bottom: 3, left: 3, right: 3 },
                textColor: TEXT_DARK, lineColor: BORDER_LIGHT, lineWidth: 0.25 },
  headStyles: { fillColor: BRAND_COLOR, textColor: [255, 255, 255],
                fontStyle: "bold", fontSize: 7.5 },
  alternateRowStyles: { fillColor: HEADER_GRAY },
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function teu(size) {
  return size === "40" || size === "40HC" || size === "45" ? 2 : 1;
}

function fmtNum(n, dec = 2) {
  if (n == null || n === "") return "—";
  return Number(n).toLocaleString("en-US", { minimumFractionDigits: dec, maximumFractionDigits: dec });
}

// Returns { doc, filename } — caller decides whether to preview or save directly.
// ─── B/L Draft ────────────────────────────────────────────────────────────────

export function generateBLDraft(shipment, containers) {
  const doc     = newDoc();
  const blNo    = shipment.blNumber || shipment.bookingRef || shipment.id;
  const fileRef = shipment.bookingRef
    ? `${shipment.id}_${shipment.bookingRef}`
    : shipment.id;
  const filename = `BL_DRAFT_${fileRef.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;

  let y = drawPageHeader(doc, "HOUSE BILL OF LADING", `DRAFT · B/L No: ${blNo}`);
  drawDraftWatermark(doc);

  y = drawSectionHeading(doc, y, "Parties");
  y = drawMetaBox(doc, y, [
    ["SHIPPER",       shipment.shipperName   || "—", "CONSIGNEE",    shipment.consigneeName || "—"],
    ["NOTIFY PARTY",  shipment.notifyName || "—",    "",             ""],
  ]);

  y = drawSectionHeading(doc, y, "Route & Vessel");
  y = drawMetaBox(doc, y, [
    ["PORT OF LOADING",   `${shipment.pol}${shipment.polName   ? " · " + shipment.polName   : ""}`,
     "PORT OF DISCHARGE", `${shipment.pod}${shipment.podName   ? " · " + shipment.podName   : ""}`],
    ["VESSEL",    shipment.vessel       || "—", "VOYAGE",  shipment.voyage       || "—"],
    ["ETD",       shipment.etd          || "—", "ETA",     shipment.eta          || "—"],
    ["INCOTERM",  shipment.incoterm     || "—", "CARRIER", shipment.carrierCode  || "—"],
  ]);

  y = drawSectionHeading(doc, y, "Container Details");

  const totalWeight = containers.reduce((s, c) => s + (c.grossWeightKg ?? 0), 0);
  const totalVol    = containers.reduce((s, c) => s + (c.volumeCbm   ?? 0), 0);
  const totalTEU    = containers.reduce((s, c) => s + teu(c.size), 0);

  autoTable(doc, {
    ...TABLE_STYLES,
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["Container No.", "Size", "Type", "Seal No.", "Gross Wt. (kg)", "Volume (cbm)", "DG"]],
    body: containers.map(c => [
      c.containerNumber || "—",
      c.size            || "—",
      c.type            || "—",
      c.sealNumber      || "—",
      fmtNum(c.grossWeightKg, 0),
      fmtNum(c.volumeCbm),
      c.isDg ? (c.dgClass || "Yes") : "—",
    ]),
    foot: [["TOTALS", `${totalTEU} TEU`, "", "", fmtNum(totalWeight, 0) + " kg", fmtNum(totalVol) + " cbm", ""]],
    footStyles: { fontStyle: "bold", fillColor: [230, 235, 245], textColor: TEXT_DARK },
  });

  y = doc.lastAutoTable.finalY + 6;

  y = drawSectionHeading(doc, y, "Cargo & Terms");
  y = drawMetaBox(doc, y, [
    ["SHIPMENT ID",  shipment.id,                  "BOOKING REF",  shipment.bookingRef || "—"],
    ["COMMODITY",    shipment.commodityCode || "—", "CONTRACT REF", shipment.contractRef || shipment.contractId || "—"],
    ["STATUS",       shipment.status        || "—", "",             ""],
  ]);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(180, 40, 40);
  doc.text("WARNING: DRAFT DOCUMENT - NOT FOR COMMERCIAL USE OR CUSTOMS PURPOSES", 14, y + 6);

  drawFooter(doc, "DRAFT HOUSE B/L - For internal review only");

  return { doc, filename };
}

// ─── Packing List ─────────────────────────────────────────────────────────────

export function generatePackingList(shipment, containers) {
  const doc     = newDoc();
  const fileRef = shipment.bookingRef
    ? `${shipment.id}_${shipment.bookingRef}`
    : shipment.id;
  const filename = `PACKING_LIST_${fileRef.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;

  let y = drawPageHeader(doc, "PACKING LIST",
    `${shipment.id}${shipment.bookingRef ? " · " + shipment.bookingRef : ""}`);

  y = drawSectionHeading(doc, y, "Shipment Details");
  y = drawMetaBox(doc, y, [
    ["SHIPMENT ID",       shipment.id,          "BOOKING REF",    shipment.bookingRef || "—"],
    ["PORT OF LOADING",   `${shipment.pol}${shipment.polName ? " · " + shipment.polName : ""}`,
     "PORT OF DISCHARGE", `${shipment.pod}${shipment.podName ? " · " + shipment.podName : ""}`],
    ["CARRIER",   shipment.carrierCode || "—",
     "VESSEL / VOYAGE", `${shipment.vessel || "—"} / ${shipment.voyage || "—"}`],
    ["ETD",       shipment.etd      || "—", "ETA",     shipment.eta     || "—"],
    ["INCOTERM",  shipment.incoterm || "—", "SHIPPER", shipment.shipperName || "—"],
  ]);

  y = drawSectionHeading(doc, y, "Cargo Details");

  const totalWeight = containers.reduce((s, c) => s + (c.grossWeightKg ?? 0), 0);
  const totalVol    = containers.reduce((s, c) => s + (c.volumeCbm   ?? 0), 0);

  autoTable(doc, {
    ...TABLE_STYLES,
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["Container No.", "Equipment", "Seal No.", "HS Code", "Description", "Gross Wt. (kg)", "Volume (cbm)"]],
    body: containers.map(c => [
      c.containerNumber  || "—",
      `${c.size || ""} ${c.type || ""}`.trim() || "—",
      c.sealNumber       || "—",
      c.hsCode           || "—",
      c.cargoDescription || "—",
      fmtNum(c.grossWeightKg, 0),
      fmtNum(c.volumeCbm),
    ]),
    columnStyles: { 4: { cellWidth: 48 } },
    foot: [["", "", "", "", "TOTALS", fmtNum(totalWeight, 0) + " kg", fmtNum(totalVol) + " cbm"]],
    footStyles: { fontStyle: "bold", fillColor: [230, 235, 245], textColor: TEXT_DARK },
  });

  drawFooter(doc);
  return { doc, filename };
}

// ─── Container Manifest ───────────────────────────────────────────────────────

export function generateContainerManifest(shipment, containers) {
  const doc     = newDoc();
  const fileRef = shipment.bookingRef
    ? `${shipment.id}_${shipment.bookingRef}`
    : shipment.id;
  const filename = `CONTAINER_MANIFEST_${fileRef.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;
  const vsv      = [shipment.vessel, shipment.voyage].filter(Boolean).join(" / ") || "—";

  let y = drawPageHeader(doc, "CONTAINER MANIFEST", `${shipment.id} · ${vsv}`);

  y = drawSectionHeading(doc, y, "Voyage Details");
  y = drawMetaBox(doc, y, [
    ["SHIPMENT ID",  shipment.id,              "BOOKING REF", shipment.bookingRef || "—"],
    ["VESSEL",       shipment.vessel  || "—",  "VOYAGE",      shipment.voyage     || "—"],
    ["CARRIER",      shipment.carrierCode || "—", "ETD",      shipment.etd        || "—"],
    ["PORT OF LOADING",   `${shipment.pol}${shipment.polName ? " · " + shipment.polName : ""}`,
     "PORT OF DISCHARGE", `${shipment.pod}${shipment.podName ? " · " + shipment.podName : ""}`],
    ["SHIPPER",  shipment.shipperName || "—", "CONSIGNEE", shipment.consigneeName || "—"],
  ]);

  y = drawSectionHeading(doc, y, "Container Listing");

  const totalWeight = containers.reduce((s, c) => s + (c.grossWeightKg ?? 0), 0);
  const totalVol    = containers.reduce((s, c) => s + (c.volumeCbm   ?? 0), 0);
  const totalTEU    = containers.reduce((s, c) => s + teu(c.size), 0);

  autoTable(doc, {
    ...TABLE_STYLES,
    startY: y,
    margin: { left: 14, right: 14 },
    head: [["#", "Container No.", "Size", "Type", "Seal No.", "Gross Wt. (kg)", "Vol. (cbm)", "DG", "Cargo Description"]],
    body: containers.map((c, i) => [
      i + 1,
      c.containerNumber  || "—",
      c.size             || "—",
      c.type             || "—",
      c.sealNumber       || "—",
      fmtNum(c.grossWeightKg, 0),
      fmtNum(c.volumeCbm),
      c.isDg ? (c.dgClass || "Yes") : "—",
      c.cargoDescription || "—",
    ]),
    columnStyles: { 8: { cellWidth: 42 } },
    foot: [[
      "", `${containers.length} ctrs`, `${totalTEU} TEU`, "", "",
      fmtNum(totalWeight, 0) + " kg", fmtNum(totalVol) + " cbm", "", "",
    ]],
    footStyles: { fontStyle: "bold", fillColor: [230, 235, 245], textColor: TEXT_DARK },
  });

  drawFooter(doc);
  return { doc, filename };
}
